bind 0.0.0.0
port 6379
requirepass 158168
appendonly yes
appendfilename "appendonly.aof"
dir /data
# 保护模式（关闭保护模式，允许外部访问）
protected-mode no

# 内存限制
maxmemory 256mb
maxmemory-policy allkeys-lru

# 连接超时（0 表示不超时）
timeout 0

# 日志级别
loglevel notice
